#!/bin/sh -e

mkdir --parents /var/lib/mireka

if ! id mireka > /dev/null 2>&1 ; then
	adduser --system --home /var/lib/mireka --no-create-home \
	--group --disabled-password --shell /bin/false \
	mireka
fi

mkdir --parents \
	/usr/share/mireka/classes \
	/var/log/mireka \
	/var/lib/mireka/maildrops \
	/var/lib/mireka/postmaster \
	/var/lib/mireka/queues/dsn \
	/var/lib/mireka/queues/retry \
	/var/lib/mireka/queues/submitted
	
ln -sfn /usr/share/mireka/bin		/var/lib/mireka/bin
ln -sfn /usr/share/mireka/classes	/var/lib/mireka/classes
ln -sfn /etc/mireka			/var/lib/mireka/conf
ln -sfn /usr/share/doc/mireka		/var/lib/mireka/doc
ln -sfn /usr/share/mireka/lib		/var/lib/mireka/lib
ln -sfn /var/log/mireka			/var/lib/mireka/log

chown -R mireka:adm /var/log/mireka
chmod 2750 /var/log/mireka
chown -R mireka:mireka /var/lib/mireka/maildrops /var/lib/mireka/postmaster /var/lib/mireka/queues
chmod 750 /var/lib/mireka/maildrops /var/lib/mireka/postmaster /var/lib/mireka/queues
chown root:mireka /etc/mireka/global-users.js
chmod 640 /etc/mireka/global-users.js

echo "0.0.0.0/0:25,25\n0.0.0.0/0:110,110\n0.0.0.0/0:587,587" | tee /etc/authbind/byuid/$(id -u mireka) > /etc/authbind/byuid/!$(id -u mireka) 

start mireka || true
